parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: tunemaps2
    database_user: username
    database_password: password
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 8313810ca6cb4f10b6d84c2f9ebf3963b8
    database_path: null
