tune_maps_front_homepage:
    pattern:  /
    defaults: { _controller: TuneMapsFrontBundle:Page:home }

tune_maps_front_mainpage:
    pattern:  /map
    defaults: { _controller: TuneMapsFrontBundle:Page:map }

tune_maps_front_timeline:
    pattern:  /timeline
    defaults: { _controller: TuneMapsFrontBundle:Page:timeline }

tune_maps_front_events:
    pattern:  /events
    defaults: { _controller: TuneMapsFrontBundle:Page:events }

tune_maps_front_trends:
    pattern:  /trends
    defaults: { _controller: TuneMapsFrontBundle:Page:trends }