# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal	

tune_maps_front:
    resource: "@TuneMapsFrontBundle/Resources/config/routing.yml"

tune_maps_user:
    resource: "@TuneMapsUserBundle/Resources/config/routing.yml"

tune_maps_player:
    resource: "@TuneMapsPlayerBundle/Resources/config/routing.yml"