tune_maps_service_artist:
    pattern:  /player/{track}/{artist}
    defaults: { _controller: TuneMapsServiceBundle:Service:artist }

tune_maps_service_track:
    pattern:  /player/{track}
    defaults: { _controller: TuneMapsServiceBundle:Service:track }
    
tune_maps_service_tracks:
    pattern: /tracks/{track}
    defaults: {_controller: TuneMapsServiceBundle:Service:tracks }

tune_maps_service_event:
    pattern: /getEvents
    defaults: {_controller: TuneMapsServiceBundle:Service:events }