tune_maps_service_artist:
    pattern:  /service/player/{track}/{artist}
    defaults: { _controller: TuneMapsServiceBundle:Service:artist }

tune_maps_service_track:
    pattern:  /service/player/{track}
    defaults: { _controller: TuneMapsServiceBundle:Service:track }
    
tune_maps_service_tracks:
    pattern:  /service/tracks/{track}
    defaults: {_controller: TuneMapsServiceBundle:Service:tracks }

tune_maps_service_event:
    pattern:  /service/events
    defaults: {_controller: TuneMapsServiceBundle:Service:events }
    
tune_maps_service_trackinfo:
    pattern:  /service/trackinfo
    defaults: {_controller: TuneMapsServiceBundle:Service:trackinfo }
    
tune_maps_service_songplayed:
    pattern:  /service/songplayed/{userid}/{songid}
    defaults: {_controller: TuneMapsServiceBundle:Service:songPlayed }
    
tune_maps_crawler_display:
    pattern:  /crawler/
    defaults: {_controller: TuneMapsServiceBundle:Crawler:display }


tune_maps_crawler_users:
    pattern:  /crawler/users/{page}
    defaults: {_controller: TuneMapsServiceBundle:Crawler:users }
    
tune_maps_service_recentTracks:
    pattern:  /crawler/recenttracks/{username}/{page}
    defaults: {_controller: TuneMapsServiceBundle:Crawler:recentTracks }
    
tune_maps_service_topTracks:
    pattern:  /crawler/toptracks/{username}/{page}
    defaults: {_controller: TuneMapsServiceBundle:Crawler:topTracks }