tune_maps_player_artist:
    pattern:  /player/{track}/{artist}
    defaults: { _controller: TuneMapsPlayerBundle:Player:artist }

tune_maps_player_track:
    pattern:  /player/{track}
    defaults: { _controller: TuneMapsPlayerBundle:Player:track }
