tune_maps_player_artist:
    pattern:  /player/{track}/{artist}
    defaults: { _controller: TuneMapsPlayerBundle:Player:artist }

tune_maps_player_track:
    pattern:  /player/{track}
    defaults: { _controller: TuneMapsPlayerBundle:Player:track }
    
tune_maps_player_tracks:
    pattern: /tracks/{track}
    defaults: {_controller: TuneMapsPlayerBundle:Player:tracks }

tune_maps_player_event:
    pattern: /events
    defaults: {_controller: TuneMapsPlayerBundle:Player:events }