tune_maps_database_metro:
    pattern:  /database/metros
    defaults: { _controller: TuneMapsRecommendationBundle:Information:metrosToDatabase }

tune_maps_database_rank:
    pattern:  /database/rank/{geo}/{start}/{end}
    defaults: { _controller: TuneMapsRecommendationBundle:Information:rankingsToDatabase }

tune_maps_rank:
    pattern:  /database/ranks
    defaults: { _controller: TuneMapsRecommendationBundle:Information:rankings }
